// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFPe0npRX-nU62Li5NG8PxB2nwvybeQbo',
    appId: '1:994745554804:web:c27b3e94fa93e4866bfe21',
    messagingSenderId: '994745554804',
    projectId: 'waslynotify',
    authDomain: 'waslynotify.firebaseapp.com',
    storageBucket: 'waslynotify.firebasestorage.app',
    measurementId: 'G-P7YRWDLB4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWX0tumAPRuq_EbzprKsD3Ae-OEl0eRu8',
    appId: '1:994745554804:android:718cf928a4d0efae6bfe21',
    messagingSenderId: '994745554804',
    projectId: 'waslynotify',
    storageBucket: 'waslynotify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4JQJpEio1uGNhOb3-PjFBblIXkh0E6QQ',
    appId: '1:994745554804:ios:558a0a8efdd7bf816bfe21',
    messagingSenderId: '994745554804',
    projectId: 'waslynotify',
    storageBucket: 'waslynotify.firebasestorage.app',
    iosBundleId: 'com.fourthpyramid.wassaly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4JQJpEio1uGNhOb3-PjFBblIXkh0E6QQ',
    appId: '1:994745554804:ios:558a0a8efdd7bf816bfe21',
    messagingSenderId: '994745554804',
    projectId: 'waslynotify',
    storageBucket: 'waslynotify.firebasestorage.app',
    iosBundleId: 'com.fourthpyramid.wassaly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFPe0npRX-nU62Li5NG8PxB2nwvybeQbo',
    appId: '1:994745554804:web:ec7fe4c290904cfc6bfe21',
    messagingSenderId: '994745554804',
    projectId: 'waslynotify',
    authDomain: 'waslynotify.firebaseapp.com',
    storageBucket: 'waslynotify.firebasestorage.app',
    measurementId: 'G-W0E5J4PM3Q',
  );

}